### ISSUE TITLE
[Feature Request] Add pretty print/indented output

### ISSUE THREAD

**Issue by druchoo** [avakar/pytoml#45]
Hello, would it be possible to add an option for pretty printed/indented output?

So we can have:

```TOML
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```

instead of:
```TOML
[[fruit]]
name = "apple"

[fruit.physical]
color = "red"
shape = "round"

[[fruit.variety]]
name = "red delicious"

[[fruit.variety]]
name = "granny smith"

[[fruit]]
name = "banana"

[[fruit.variety]]
name = "plantain"
```
